### ISSUE TITLE
e1 exercise  error report

### ISSUE THREAD

**Issue by suinming** [devslopes/functions-practice-unsolved#1]
In the e1 exercise line 63,   * The function of logs a message of 'My name is <name>, I am <age> years old!'.
The comma should be replaced by dot to pass the unit test.

* The function of logs a message of 'My name is <name>, I am <age> years old!'.
 change to 
* The function of logs a message of 'My name is <name>. I am <age> years old!'.

**Comment by andreycodez** [comment]
Agree, the task has a comma on line 57 and a period on line 60. fixed both to say ".".
